name: Makefile CI

on:
  push:
    branches: [ "zi" ]
  pull_request:
    branches: [ "zi" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install .NET
      run: sudo apt install dotnet-sdk-7.0

    - name: Build project
      run: make build
